# 强制指定为 Node.js 项目，避免识别成 Java/Maven
language: node_js
node_js:
  - 20

name: 前端自动部署到Windows2012R2
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装pnpm
        run: npm install -g pnpm

      - name: 安装依赖
        run: |
          export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
          pnpm install --frozen-lockfile

      - name: 构建项目
        run: pnpm run build

      - name: 部署到Windows服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WIN_SERVER_IP }}
          username: ${{ secrets.WIN_SERVER_USER }}
          password: ${{ secrets.WIN_SERVER_PWD }}
          port: 22
          source: 'dist/*'
          target: 'C:/phpstudy_pro/WWW/project/vue_project/'
          strip_components: 1
          timeout: 30s