/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CityPicker: typeof import('./../components/business/CityPicker.vue')['default']
    DialogStackExample: typeof import('./../components/base/DialogStackExample.vue')['default']
    EmptyState: typeof import('./../components/base/EmptyState.vue')['default']
    ImageCard: typeof import('./../components/business/ImageCard.vue')['default']
    ImagePreview: typeof import('./../components/base/ImagePreview.vue')['default']
    LazyImage: typeof import('./../components/base/LazyImage.vue')['default']
    LoadingToast: typeof import('./../components/base/LoadingToast.vue')['default']
    LoadMore: typeof import('./../components/base/LoadMore.vue')['default']
    NativeSwipeTabs: typeof import('./../components/base/NativeSwipeTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/base/SearchBar.vue')['default']
    StoreItem: typeof import('./../components/page/home/StoreItem.vue')['default']
    StoreList: typeof import('./../components/business/StoreList.vue')['default']
    SwipeTabs: typeof import('./../components/base/SwipeTabs.vue')['default']
    TargetMap: typeof import('./../components/base/TargetMap.vue')['default']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanLoading: typeof import('vant/es')['Loading']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
