/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CityPicker: typeof import('./../components/business/CityPicker.vue')['default']
    copy: typeof import('./../components/base/ImagePreview copy.vue')['default']
    EmptyState: typeof import('./../components/base/EmptyState.vue')['default']
    ImagePreview: typeof import('./../components/base/ImagePreview.vue')['default']
    'ImagePreview copy': typeof import('./../components/base/ImagePreview copy.vue')['default']
    ImagePreviewModal: typeof import('./../components/base/ImagePreviewModal.vue')['default']
    LazyImage: typeof import('./../components/base/LazyImage.vue')['default']
    LoadingToast: typeof import('./../components/base/LoadingToast.vue')['default']
    LoadMore: typeof import('./../components/base/LoadMore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/base/SearchBar.vue')['default']
    StoreItem: typeof import('./../components/page/home/StoreItem.vue')['default']
    StoreList: typeof import('./../components/business/StoreList.vue')['default']
    SwipeTabs: typeof import('./../components/base/SwipeTabs.vue')['default']
    TargetMap: typeof import('./../components/base/TargetMap.vue')['default']
    VanLoading: typeof import('vant/es')['Loading']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
