version: '1.0'
name: '123456789'
displayName: '1111'
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-cb899d3a
    displayName: '111'
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: ''
        image: node:20
        command:
          - '# 简化版调试脚本（只做构建，不传文件）'
          - '#!/bin/bash'
          - set -e
          - git clone --depth 1 https://gitee.com/harlan123/corner.git .
          - npm install -g pnpm
          - export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
          - pnpm install --frozen-lockfile
          - pnpm run build
          - '# 打印目录，确认 dist 生成'
          - ls -l
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        notify: []
        strategy:
          retry: '0'
