version: '1.0'
name: '123456789'
displayName: '1111'
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-cb899d3a
    displayName: '111'
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: ''
        image: node:20
        command:
          - '#!/bin/sh'
          - set -e
          - '# 1. 生成测试 txt 文件（内容随便写）'
          - echo "这是 Gitee 流水线生成的测试文件" > test.txt
          - '# 2. 安装 scp 工具（alpine 镜像需要装）'
          - apk add openssh-client sshpass
          - '# 3. 把 txt 传到你的 Windows 服务器（改下面 3 个地方！）'
          - sshpass -p "你的Windows登录密码" scp -P 22 test.txt \
          - '  "administrator@101.33.227.33:C:/phpstudy_pro/WWW/project/vue_project/"'
        notify: []
        strategy:
          retry: '0'
