name: Frontend CI/CD
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      deploy_only:
        type: boolean
        description: '仅执行部署（跳过构建）'
        required: false
        default: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 远程解压 1.tar.gz
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          # 关键：给带空格的 tar.exe 路径加双引号
          script: |
            cmd /c "cd /d C:\phpstudy_pro\WWW\project\vue_project\front\test && ""C:\Program Files\Git\usr\bin\tar.exe"" -zxvf 1.tar.gz"